#pragma once
namespace Client
{
	enum SCENE { SCENE_STATIC, SCENE_LOGO, SCENE_LOBBY, SCENE_LOADING, SCENE_GAMEPLAY, SCENE_TEST, SCENE_EFFECT, SCENE_END };

	enum class	EQUIPMENTGROUP { BASE, WEAPON, MAGAZINE, GEAR };
	enum class  EQUIPMENT : int { PRIMARY, PRIMARYMAG, SECONDARY, SECONDARYMAG, GRENADE, TOOL, HEADGEAR, TORSO, LEGS, VEST, BACKPACK, NONE };
	enum class  GEAR : int { HEADGEAR, TORSO, LEGS, VEST, BACKPACK, NONE };

	enum class	VISIBILITY { VISIBLE, INVISIBLE, NONE };
}